### ISSUE TITLE
先找个项目吧

### ISSUE THREAD

**Issue by hsz1273327** [NLP-Deeplearning-Club/kaggle-project#1]
先这么多

**Comment by hsz1273327** [comment]
武汉学长正在做的<https://www.kaggle.com/c/statoil-iceberg-classifier-challenge/>

**Comment by alphafan** [comment]
NLP 项目
https://www.kaggle.com/c/quora-question-pairs

**Comment by alphafan** [comment]
推荐系统，我正在做的：
https://www.kaggle.com/c/kkbox-music-recommendation-challenge

**Comment by hsz1273327** [comment]
最终挑选了[tensorflow的语音识别项目](https://www.kaggle.com/c/tensorflow-speech-recognition-challenge)
